### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by HuKeping** [HuKeping/rbtree#15]
Hi there,
Below is what I supposed to do  but things get a little busy these days, however I will keep working on it and if any of you have time to help, PR is welcome :)
- [ ] comment for function `deleteFixup`
- [ ] more iterators
- [ ] docs for usage
- [ ] a function that get the height of the tree
- [ ] enhance test
- [ ] more examples
- [ ] a function that get the successor of the given Item
- [x] add a new file to hold states of the tree. For example, the length, the min, the max, etc. #16
